In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import *
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

C:\Users\rajusuja.CORPDOM\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [38]:
dataset = pd.read_csv("learning LetsUpgrade/Day24/train.csv")
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

# PreProcessing

In [39]:
dataset["Sex"] = preprocessing.LabelEncoder().fit_transform(dataset["Sex"])

In [36]:
print(le2.classes_)

['C' 'Q' 'S']


In [40]:
# Transforming gender values in Sex varaiable to binary numbers

dataset["Embarked"] = preprocessing.LabelEncoder().fit_transform(dataset["Embarked"])

# Using PClass as the Response or Dependent variable

In [41]:
y = dataset["Sex"] # DV

In [18]:
list=[]
list = dataset.drop(["PassengerId","Cabin","Ticket","Name"],axis=1)
print(list)
list

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  22.0      1      0    7.2500        S
1           1       1  female  38.0      1      0   71.2833        C
2           1       3  female  26.0      0      0    7.9250        S
3           1       1  female  35.0      1      0   53.1000        S
4           0       3    male  35.0      0      0    8.0500        S
5           0       3    male  45.0      0      0    8.4583        Q
6           0       1    male  54.0      0      0   51.8625        S
7           0       3    male   2.0      3      1   21.0750        S
8           1       3  female  27.0      0      2   11.1333        S
9           1       2  female  14.0      1      0   30.0708        C
10          1       3  female   4.0      1      1   16.7000        S
11          1       1  female  58.0      0      0   26.5500        S
12          0       3    male  20.0      0      0    8.0500        S
13          0       3    male  39.

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  22.0      1      0    7.2500        S
1           1       1  female  38.0      1      0   71.2833        C
2           1       3  female  26.0      0      0    7.9250        S
3           1       1  female  35.0      1      0   53.1000        S
4           0       3    male  35.0      0      0    8.0500        S
5           0       3    male  45.0      0      0    8.4583        Q
6           0       1    male  54.0      0      0   51.8625        S
7           0       3    male   2.0      3      1   21.0750        S
8           1       3  female  27.0      0      2   11.1333        S
9           1       2  female  14.0      1      0   30.0708        C
10          1       3  female   4.0      1      1   16.7000        S
11          1       1  female  58.0      0      0   26.5500        S
12          0       3    male  20.0      0      0    8.0500        S
13          0       3    male  39.0      1      5   31.2750        S
14          0       3  female  14.0      0      0    7.8542        S
15          1       2  female  55.0      0      0   16.0000        S
16          0       3    male   2.0      4      1   29.1250        Q
17          1       2    male  45.0      0      0   13.0000        S
18          0       3  female  31.0      1      0   18.0000        S
19          1       3  female  45.0      0      0    7.2250        C
20          0       2    male  35.0      0      0   26.0000        S
21          1       2    male  34.0      0      0   13.0000        S
22          1       3  female  15.0      0      0    8.0292        Q
23          1       1    male  28.0      0      0   35.5000        S
24          0       3  female   8.0      3      1   21.0750        S
25          1       3  female  38.0      1      5   31.3875        S
26          0       3    male  45.0      0      0    7.2250        C
27          0       1    male  19.0      3      2  263.0000        S
28          1       3  female  45.0      0      0    7.8792        Q
29          0       3    male  45.0      0      0    7.8958        S
..        ...     ...     ...   ...    ...    ...       ...      ...
859         0       2    male  21.0      1      0   11.5000        S
860         1       1  female  48.0      0      0   25.9292        S
861         0       3  female  45.0      8      2   69.5500        S
862         0       2    male  24.0      0      0   13.0000        S
863         1       2  female  42.0      0      0   13.0000        S
864         1       2  female  27.0      1      0   13.8583        C
865         0       1    male  31.0      0      0   50.4958        S
866         0       3    male  45.0      0      0    9.5000        S
867         1       3    male   4.0      1      1   11.1333        S
868         0       3    male  26.0      0      0    7.8958        S
869         1       1  female  47.0      1      1   52.5542        S
870         0       1    male  33.0      0      0    5.0000        S
871         0       3    male  47.0      0      0    9.0000        S
872         1       2  female  28.0      1      0   24.0000        C
873         1       3  female  15.0      0      0    7.2250        C
874         0       3    male  20.0      0      0    9.8458        S
875         0       3    male  19.0      0      0    7.8958        S
876         0       3    male  45.0      0      0    7.8958        S
877         1       1  female  56.0      0      1   83.1583        C
878         1       2  female  25.0      0      1   26.0000        S
879         0       3    male  33.0      0      0    7.8958        S
880         0       3  female  22.0      0      0   10.5167        S
881         0       2    male  28.0      0      0   10.5000        S
882         0       3    male  25.0      0      0    7.0500        S
883         0       3  female  39.0      0      5   29.1250        Q
884         0       2    male  27.0      0      0   13.0000        S
885

In [53]:
def choose_column(label):
    print(label)
    X = dataset.drop([label,"PassengerId","Cabin","Ticket","Name"],axis=1)
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state=0)
    bnl = BernoulliNB()
    y_pred = bnl.fit(X_train,y_train).predict(X_test)
    conf_matrix = confusion_matrix(y_test,y_pred)
    print(len(conf_matrix))
    print("\n..Accuracy_Score for label",label," is..\n")
    print(accuracy_score(y_test,y_pred,normalize=True))
    print("\n..Confusion Matrix for label",label," is..\n")
    print(confusion_matrix(y_test,y_pred))
    print("Total",np.sum(confusion_matrix(y_test,y_pred)))
    print("Correct",np.trace(confusion_matrix(y_test,y_pred)))
    print("=========End of ",label,"===============================")
    
for i in list.columns:
    print(i)
    choose_column(i)

Survived
Survived
2

..Accuracy_Score for label Survived  is..

1.0

..Confusion Matrix for label Survived  is..

[[ 98   0]
 [  0 169]]
Total 267
Correct 267
=========End of  Survived ===============================
Pclass
Pclass
2

..Accuracy_Score for label Pclass  is..

1.0

..Confusion Matrix for label Pclass  is..

[[ 98   0]
 [  0 169]]
Total 267
Correct 267
=========End of  Pclass ===============================
Sex
Sex
2

..Accuracy_Score for label Sex  is..

0.7453183520599251

..Confusion Matrix for label Sex  is..

[[ 49  49]
 [ 19 150]]
Total 267
Correct 199
=========End of  Sex ===============================
Age
Age
2

..Accuracy_Score for label Age  is..

1.0

..Confusion Matrix for label Age  is..

[[ 98   0]
 [  0 169]]
Total 267
Correct 267
=========End of  Age ===============================
SibSp
SibSp
2

..Accuracy_Score for label SibSp  is..

1.0

..Confusion Matrix for label SibSp  is..

[[ 98   0]
 [  0 169]]
Total 267
Correct 267
=========End of  SibSp =======

# total = 267
# correct = 267 = 100%
# Incorrect = 0 = 0%
