# 1. Create a 3x3x3 array with random values 

In [215]:
import numpy as np

x = np.random.random((3,3,3))

print(x)

[[[0.47981306 0.95537066 0.46301871]
  [0.55602456 0.68967773 0.34526813]
  [0.03484685 0.76690839 0.71484483]]

 [[0.72747227 0.97780961 0.49208884]
  [0.45023742 0.28960985 0.4527397 ]
  [0.44867226 0.33239816 0.94487144]]

 [[0.13931527 0.06135434 0.52889971]
  [0.16481607 0.46833689 0.49941778]
  [0.80744565 0.97176591 0.44230765]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [16]:
x = np.array([1,2,3,4])
y = np.diag(x, k=-1)
y

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [21]:
b = np.zeros((8,8))
b[1::2,::2] = 1
b[::2, 1::2]= 1
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [43]:
c = np.random.random((5,5))
Cmax,Cmin=c.max(),c.min()
c= (c-Cmin)/(Cmax-Cmin)
c

array([[0.90510877, 0.83585683, 0.81794724, 1.        , 0.30111835],
       [0.        , 0.99108144, 0.10283679, 0.45507866, 0.43107071],
       [0.09211681, 0.17565303, 0.16340824, 0.15929999, 0.54680126],
       [0.31307272, 0.43597979, 0.91887617, 0.62481674, 0.26412714],
       [0.45006664, 0.1182058 , 0.39266259, 0.81332897, 0.99851978]])

# 5.  How to find common values between two arrays?

In [44]:
a = np.array([2,4,6,8,10])
b = np.array([4,8,12,16,20])
c = np.intersect1d(a,b)
c

array([4, 8])

# 6.How to get the dates of yesterday, today and tomorrow?

In [55]:
today = np.datetime64('today')
yesturday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)
print('Todays Date: ',today)
print('Yesturday Date: ',yesturday)
print('Tomorrow Date: ',tomorrow)

Todays Date:  2020-07-25
Yesturday Date:  2020-07-24
Tomorrow Date:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [71]:
Arr1 = np.random.randint(2,3,4)
Arr3 = np.random.randint(2,3,4)
Arr2 = np.random.randint(2,5,4)
EqCheck = np.allclose(Arr1,Arr3)
NEqCheck = np.allclose(Arr1,Arr2)
print('Equals check',EqCheck)
print('Unequals check',NEqCheck)

Equals check True
Unequals check False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [85]:
ran1 = np.random.random(10)
ran1[ran1.argmax()] = 0
print(ran1)

[0.37283045 0.96542887 0.35025673 0.70981447 0.         0.55968057
 0.66996216 0.88866314 0.12412023 0.54204539]


# 9. How to print all the values of an array?

In [89]:
arr = np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [117]:
print("Original matrix:\n")
X = np.random.rand(3,4)
print(X)
print('\nMean of Original Matrix: ',X.mean())
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean()
#Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.25956831 0.50891504 0.5338252  0.27350408]
 [0.21151515 0.8938227  0.84026648 0.80534527]
 [0.69612058 0.07669407 0.35239772 0.81566801]]

Mean of Original Matrix:  0.5223035508254027

Subtract the mean of each row of the said matrix:

[[-0.26273524 -0.01338851  0.01152165 -0.24879947]
 [-0.3107884   0.37151915  0.31796293  0.28304172]
 [ 0.17381703 -0.44560948 -0.16990584  0.29336446]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [169]:
vec = np.ones(5)

I = np.random.randint(0,len(vec),7)
print('I:', I)
vec = vec + np.bincount(I, minlength=len(vec))
print(vec)

I: [4 0 4 2 4 2 0]
[3. 1. 3. 1. 4.]


# 12.How to get the diagonal of a dot product?

In [221]:
u = [[2,-3],[1,9]]
v = [[0,1],[1,-4]]

w = np.dot(u,v)
print('dot product is:',w)

print('Diagnol of dot product is: ',np.diag(w))




dot product is: [[ -3  14]
 [  9 -35]]
Diagnol of dot product is:  [ -3 -35]


# 13.How to find the most frequent value in an array?

In [184]:
freqVal = np.random.randint(1,10,25)
print('All number:',freqVal)
print(np.bincount(freqVal).argmax())


All number: [9 7 1 5 4 6 5 6 7 9 5 1 2 7 3 3 1 2 7 4 7 5 6 9 4]
7


# 14.How to get the n largest values of an array

In [197]:
freqVal = np.random.randint(1,20,10)
print('All number:',freqVal)
print('Index of an arry:',np.argsort(freqVal))
print(freqVal[np.argsort(freqVal)[-1:]])

All number: [ 6  1  6 15 18  7 15  8  9 10]
Index of an arry: [1 0 2 5 7 8 9 3 6 4]
[18]


# 15.How to create a record array from a regular array?

In [214]:
import numpy as np
arra1 = np.array([("Suresh", 82.5, 85),
                 ("Ramesh", 68, 80),
             ("Jony", 87.3, 99),
                ("Reshma", 77.2, 95)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3')
print(result)

Original arrays:
[['Suresh' '82.5' '85']
 ['Ramesh' '68' '80']
 ['Jony' '87.3' '99']
 ['Reshma' '77.2' '95']]

Record array;
[('Suresh', '82.5', '85') ('Ramesh', '68', '80') ('Jony', '87.3', '99')
 ('Reshma', '77.2', '95')]


In [213]:
x1=np.array([1,2,3,4])
x2=np.array(['Abs','Chest','biceps','triceps'])
x3=np.array([30,34,15,5])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r)
print(r.a)
print(r.b)
print(r.c)

[(1, 'Abs', 30) (2, 'Chest', 34) (3, 'biceps', 15) (4, 'triceps',  5)]
[1 2 3 4]
['Abs' 'Chest' 'biceps' 'triceps']
[30 34 15  5]
